---
- name: Step 1 - Connect to Windows Clients
  hosts: windows_clients
  gather_facts: no
  tasks:
    - name: Trigger Windows Update Scan (WSUS)
      win_shell: powershell.exe -Command "UsoClient.exe StartScan"

    - name: Get Client Hostname
      win_command: hostname
      register: client_hostname

    - name: Save hostname into hostvars
      set_fact:
        wsus_client_hostname: "{{ client_hostname.stdout | trim }}"

- name: Step 2 - Collect and Show All Client Hostnames
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Build list of client hostnames
      set_fact:
        all_client_hostnames: "{{ groups['windows_clients'] | map('extract', hostvars, 'wsus_client_hostname') | list }}"

    - name: Show all client hostnames (GUI-friendly)
      debug:
        msg: "WSUS Clients: {{ all_client_hostnames }}"
