---
- name: Step 1 - Get WSUS Clients
  hosts: wsus_server
  gather_facts: no
  tasks:
    - name: Query WSUS for registered clients
      win_shell: |
        Import-Module UpdateServices
        Get-WsusServer | Get-WsusComputer | Select-Object -ExpandProperty FullDomainName
      register: wsus_clients

    - name: Show WSUS Clients (raw list)
      debug:
        msg: "{{ wsus_clients.stdout_lines }}"

- name: Step 2 - Report Clients in GUI-friendly format
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Save WSUS client hostnames
      set_fact:
        wsus_client_list: "{{ hostvars[groups['wsus_server'][0]].wsus_clients.stdout_lines | map('trim') | list }}"

    - name: Show consolidated WSUS clients
      debug:
        msg: "WSUS Clients: {{ wsus_client_list }}"
