---
- name: Step 1 - Get WSUS Clients from "Servers" group
  hosts: wsus_server
  gather_facts: no
  tasks:
    - name: Query WSUS server for registered clients in "Servers" group
      win_shell: |
        Import-Module UpdateServices
        $wsus = Get-WsusServer
        $group = $wsus.GetComputerTargetGroups() | Where-Object { $_.Name -eq "Servers" }
        $group.GetComputerTargets() | Select-Object -ExpandProperty FullDomainName
      register: wsus_servers

    - name: Show WSUS clients (each on a new line)
      debug:
        msg: "{{ wsus_servers.stdout_lines | join('\n') }}"

- name: Step 2 - Format and save WSUS clients to CSV
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set fact for cleaned WSUS server list
      set_fact:
        wsus_server_list: "{{ hostvars[groups['wsus_server'][0]].wsus_servers.stdout_lines | map('trim') | list }}"

    - name: Show formatted WSUS server list
      debug:
        msg: "{{ wsus_server_list | join('\n') }}"

    - name: Save WSUS server list to CSV file
      copy:
        dest: "/tmp/wsus_server_list.csv"
        content: |
          Hostname
          {% for host in wsus_server_list %}
          {{ host }}
          {% endfor %}
      delegate_to: localhost

- name: Step 3 - Copy CSV to Windows workstation
  hosts: my_windows_pc
  gather_facts: no
  tasks:
    - name: Copy CSV report to Downloads folder on Windows PC
      ansible.windows.win_copy:
        src: /tmp/wsus_server_list.csv
        dest: C:\Users\P-SVE7FZ\Downloads\wsus_server_list.csv
