---
- name: Step 1 - Get WSUS Clients from "Servers" group and scan for updates
  hosts: wsus_server
  gather_facts: no
  tasks:
    - name: Query WSUS server for registered clients in "Servers" group
      win_shell: |
        Import-Module UpdateServices
        $wsus = Get-WsusServer
        $group = $wsus.GetComputerTargetGroups() | Where-Object { $_.Name -eq "Servers" }
        $group.GetComputerTargets() | Select-Object -ExpandProperty FullDomainName
      register: wsus_servers

    - name: Set fact for clean list of WSUS clients
      set_fact:
        wsus_server_list: "{{ wsus_servers.stdout_lines | map('trim') | list | unique }}"

    - name: Add WSUS clients to dynamic group
      add_host:
        name: "{{ item }}"
        groups: wsus_dynamic
      loop: "{{ wsus_server_list }}"

# ---------------------------------------------
# STEP 2: Scan and collect pending updates
# ---------------------------------------------
- name: Step 2 - Scan WSUS clients for pending updates
  hosts: wsus_dynamic
  gather_facts: no
  tasks:
    - name: Scan for pending updates
      win_updates:
        state: searched
      register: update_scan_result

    - name: Set fact with pending updates
      set_fact:
        pending_updates: "{{ update_scan_result.updates | map(attribute='title') | list }}"

    - name: Add results to patch report on localhost
      set_fact:
        patch_report: "{{ hostvars.localhost.patch_report | default({}) | combine({inventory_hostname: pending_updates}) }}"
      delegate_to: localhost
      run_once: false

# ---------------------------------------------
# STEP 3: Save Report and Transfer to Windows
# ---------------------------------------------
- name: Step 3 - Save patch report to CSV and transfer to Windows
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure patch report directory exists
      file:
        path: /tmp/wsus_patch_report
        state: directory
        mode: '0755'

    - name: Generate CSV from patch_report
      copy:
        dest: "/tmp/wsus_patch_report/wsus_pending_patches.csv"
        content: |
          Hostname,Pending Patches
          {% for host, patches in patch_report.items() %}
          {{ host }},{"{{ patches | join('; ') if patches | length > 0 else 'No pending updates' }}"}
          {% endfor %}

- name: Step 4 - Copy final CSV to Windows PC
  hosts: my_windows_pc
  gather_facts: no
  tasks:
    - name: Copy patch report to Downloads folder on Windows PC
      ansible.windows.win_copy:
        src: /tmp/wsus_patch_report/wsus_pending_patches.csv
        dest: C:\Users\P-SVE7FZ\Downloads\wsus_pending_patches.csv
