---
- name: Step 1 - Get WSUS Clients from Servers group
  hosts: wsus_server
  gather_facts: no
  tasks:
    - name: Query WSUS Servers group for registered clients
      win_shell: |
        Import-Module UpdateServices
        $wsus = Get-WsusServer
        $group = $wsus.GetComputerTargetGroups() | Where-Object { $_.Name -eq "Servers" }
        $group.GetComputerTargets() | Select-Object -ExpandProperty FullDomainName
      register: wsus_servers

    - name: Show WSUS Servers (raw list)
      debug:
        msg: "{{ wsus_servers.stdout_lines }"

