---
- name: Step 1 - Connect to WSUS Server
  hosts: wsus_server
  gather_facts: no
  tasks:
    - name: Ping WSUS server
      win_ping:

    - name: Report WSUS Hostname
      win_hostname:

- name: Step 2 - Connect to Windows Clients 
  hosts: windows_clients
  gather_facts: no
  tasks:

    - name: Trigger Windows Update Scan (WSUS)
      win_shell: powershell.exe -Command "UsoClient.exe StartScan"
