---
- name: Step 1 - Get WSUS Clients from Servers group
  hosts: wsus_server
  gather_facts: no
  tasks:
    - name: Query WSUS Servers group for registered clients
      win_shell: |
        Import-Module UpdateServices
        $wsus = Get-WsusServer
        $group = $wsus.GetComputerTargetGroups() | Where-Object { $_.Name -eq "Servers" }
        $group.GetComputerTargets() | Select-Object -ExpandProperty FullDomainName
      register: wsus_servers

    - name: Show WSUS Servers (raw list - one per line)
      debug:
        msg: "{{ wsus_servers.stdout_lines | join('\n') }}"

- name: Step 2 - Report Servers in GUI-friendly format
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Save WSUS server hostnames as list
      set_fact:
        wsus_server_list: "{{ hostvars[groups['wsus_server'][0]].wsus_servers.stdout_lines | map('trim') | list }}"

    - name: Show consolidated WSUS servers (each on a new line)
      debug:
        msg: "{{ wsus_server_list | join('\n') }}"

    - name: Save WSUS server list to CSV file on control node
      copy:
        dest: "/tmp/wsus_server_list.csv"
        content: |
          Hostname
          {{ wsus_server_list | join('\n') }}
      delegate_to: localhost

- name: Step 3 - Download CSV to local machine
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch CSV file to local machine
      fetch:
        src: /tmp/wsus_server_list.csv
        dest: ./wsus_server_list.csv
        flat: yes
